### ISSUE TITLE
Provide a time-based discovery cache ?

### ISSUE THREAD

**Issue by strk** [yohcop/openid-go#45]
I noticed the nonce store is time-based (1 minute lifetime) -- how about also providing a time-based discovery cache ? Am I right that the discovery cache would make changes to the OpenID URI page invisible once the discovered information is cached, at the moment ?

**Comment by yohcop** [comment]
Hi,

The DiscoveryCache is just an interface, there is no implementation provided. The SimpleDiscoveryCache is only here for demo purpose, it's memory usage is unbounded (well, I guess there isn't that many discovered info to put in), and you may want something that survives binary restarts (databased backed).

So you can definitely implement one that is time based. The interface to implement is trivial:
```go
type DiscoveryCache interface {
	Put(id string, info DiscoveredInfo)
	// Return a discovered info, or nil.
	Get(id string) DiscoveredInfo
}
```

I guess you would just save the current time in `Put`, and check it in `Get`.

**Comment by strk** [comment]
PR ready, I think it's useful to have a simple one in code.

**Comment by yohcop** [comment]
Thanks for sending this. But I don't think I would like to have specific implementations in the library.
This implementation is still unbounded in memory (if you keep discovering new info, memory will grow forever).

Maybe it would be fine in the examples directory on its own, or maybe better in some other repo with a link in the README. Mostly because I still think this kind of things should be implementation specific (e.g. I'd implement it with a Redis backend for one project, Appengine's datastore on another, memcache, etc). And all these implementations shouldn't go in the main library.

What do you think?

**Comment by xStrom** [comment]
I'm using a datastore backed implementation of nonce store & discovery cache. Unbounded in DB storage usage at that.

Given the wide variety of infrastructure situations that this library can be used in I think it's valid to only have the interfaces. However the reality is that a lot of people are just looking for turnkey solutions they can immediately use. In that light it can be very useful to have some options that can be used to get started.

I don't really have an opinion of whether this repo should contain a collection of implementations. However if we do, I think separating them more clearly is the way to go. Perhaps even in distinct sub-packages. We should also migrate the Simple implementations then, as opposed to having them being part of the main package.

**Comment by strk** [comment]
@yohcop it's just a slightly more usable cache, given time is already used for the nonce store. I agree the actual implementation would better be outside, but for quick&dirty usages, the provided example could be good to have (maybe in another file/package, true)

**Comment by yohcop** [comment]
Why is it more "usable" than the current "SimpleCache"? One now has to decide what is a "good" cache expiration time. Is it a year? a week? 10 seconds? What's a sensible value? So I don't think it's any easier.

For a quick and dirty setup, i.e. just to try the library / write a toy app. In that case, the SimpleCache should be enough, no need for expiration of the discovery cache at all.

In fact, I'm thinking maybe SimpleCache should maybe not cache anything, and always return `nil` to `Get(id)`. It's not a big deal.

And time is used for the nonce store, because it is pretty much included [in the spec](http://openid.net/specs/openid-authentication-2_0.html#verify_nonce).
The discovery cache is on the other hand up to the implementation to decide what is a good duration, if not infinity, or no cache at all.

**Comment by strk** [comment]
You convinced me, I moved the proposed code into the application (Gitea)
and for now I'm ok. Feel free to close this out.

**Comment by yohcop** [comment]
Ok!
So I'm going to close this one. I added to the README a few links to libraries I randomly found on GitHub that provide implementations for database-backed nonce store/discovery cache. Looking very quickly I didn't see any that have an expiring discovery cache, but maybe that could help potential new users to get started.
