### ISSUE TITLE
 Nonce too old

### ISSUE THREAD

**Issue by mlitanin** [yohcop/openid-go#6]
Using your example I got such error: " Nonce too old" What can I do?

And could you be more specific about your comment:
// For the demo, we use in-memory infinite storage nonce and discovery
// cache. In your app, do not use this as it will eat up memory and never
// free it. Use your own implementation, on a better database system.
// If you have multiple servers for example, you may need to share at least
// the nonceStore between them.

what is "own better implementation"? How to do this? I don't understand quite good meaning of nonce and discovery cache.. sorry.

THank you for any kind of help.

**Comment by Gacnt** [comment]
@yohcop Hi, as somebody that is new to Golang and come from Node.js, packages that deal with OpenID are usually pretty self enclosed and easy to implement. Yours is quite nice as well but if you ever get free time would you be able to implement an example of how you would store your nonce and discovery in a database and query against it? Thanks.

**Comment by yohcop** [comment]
Hi,
I don't think I will implement an example with a full database. The reason is simply that if I implement one with say Redis, the next person will come and ask to implement one with MySQL, then MongoDB, etc. The other reason, is that there is already such an example, but instead of using a database, it's using an in-memory map, but the idea is the same.

The interface you have to implement for the NonceStore is very simple though:

    type NonceStore interface {
    	// Returns nil if accepted, an error otherwise.
    	Accept(endpoint, nonce string) error
    }

You only have to implement one function: `Accept`. There is an example: `SimpleNonceStore`. You could start with that, but replace the map with a database. You also have to implement a DiscoveryCache interface, and once again, there is a basic example using an in-memory map object, `SimpleDiscoveryCache`. Same story: try replacing the map with a database (a database can be seen as a bunch of key-value pairs, just like a map is)

Read more about OpenID. It's important to understand what the discovery data is - as well as how nonces work - if you want to implement a secure and working system. There are important security implications for every decision you make implementing those, so it is hard to give a one-size-fits-all implementation. Every system will want to use some database or another, and I do not want to pull in more dependencies into this project.

Good luck!

**Comment by Gacnt** [comment]
Hi thanks for your response. I guess I'm just to knew to Go yet to fully
understand how to do it. I'll just stick with Node for now :)

**Comment by Gacnt** [comment]
Hey sorry for using your issues for something such as this, I have tried making a database storage for nonce/discovery cache but I'm not sure if I was doing it right:

https://github.com/Gacnt/mysqlOpenID

I was wondering if you'd be able to contribute to it at all or point me in the right direction. Thanks, again sorry.
